### PR TITLE
Code Formatting

### PR DESCRIPTION
**Pull request by zkneupper**
Ran automatic code formatting with the following git pre-commit hooks:
+ black
+ trailing-whitespace-fixer
+ end-of-file-fixer
+ add-trailing-comma

Added a pre-commit config file in case any contributors would like to use these pre-commit git hooks going forward.

### CODE REVIEW

**Comment by zkneupper** [comment]
Here are links to the docs for the pre-commit and black python packages:
https://pre-commit.com/
https://black.readthedocs.io/en/stable/

**Comment by HugoCMU** [comment]
image
Had a little mini heart attack until I read your comment and realized this is a formatting PR.

**Comment by HugoCMU** [comment]
LGTM, @nponte-zumo @kory-zumo could you guys give this a once over and make sure there aren't any crypto mining scripts secretly being commited.

**Comment by nponte-zumo** [comment]
Good PR. 

Going to use the suggested `black` package here and add it to Github Actions to auto run these on push so that we can make this more automatic and less of a manual process.

https://github.com/ZumoLabs/zpy/pull/90

Also from what I can tell black already does`trailing-whitespace-fixer`, `end-of-file-fixer` and `add-trailing-comma` so I think just running black will fulfill that purpose.

**Comment by zkneupper** [comment]
> Good PR.
> 
> Going to use the suggested `black` package here and add it to Github Actions to auto run these on push so that we can make this more automatic and less of a manual process.
> 
> #90
> 
> Also from what I can tell black already does`trailing-whitespace-fixer`, `end-of-file-fixer` and `add-trailing-comma` so I think just running black will fulfill that purpose.

One thing to note is that black only works on `*.py` files.  However, if you use `trailing-whitespace-fixer` and `end-of-file-fixer`, those hooks will apply to all files (including `*.sh`, `*.md`, `*.txt`, `*.cfg`, etc.).

**Comment by nponte-zumo** [comment]
Yeah its a valid concern.  Unfortunately most of the GitHub actions I found only do language specific lint actions. 

I think our plan is to move out most of the documentation out of `zpy` and combine it with the rest of our workflows docs in order to give users the full picture on how to generate data (work on scene with zpy, upload with cli, gain insights from webapp). So I think for this repo just linting python is probably fine for now the automated workflow I think makes it worth the negative.

https://github.com/ZumoLabs/zpy/issues/66

**Pull request closed without merging**
